version: "3.9"

services:
  # ------------------------------------------------------------
  # MSSQL - Database
  # ------------------------------------------------------------
  db:
    container_name: mssql
    build: ./src/database
    environment:
      - ACCEPT_EULA=Y
      - TZ=Europe/Paris
      - MSSQL_SA_PASSWORD=${MSSQL_PASSWORD}
      - MSSQL_TCP_PORT=${MSSQL_PORT}
    volumes:
      - msdata:/var/lib/mssql/data
    ports:
      - ${MSSQL_PORT}:${MSSQL_PORT}
    networks:
      - matcha-network
    restart: always

  # ------------------------------------------------------------
  # ASP.NET 7.0 Core - Backend
  # ------------------------------------------------------------
  backend:
    container_name: backend
    build:
      context: ./src/backend
    hostname: backend
    environment:
      - TZ=Europe/Paris
      - ConnectionStrings__DefaultConnection=Data Source=db;Initial Catalog=${DB_NAME};User ID=sa;Password=${MSSQL_PASSWORD};Encrypt=False
      - AppSettings:FrontendHost=http://localhost:${FRONTEND_PORT}
      - AppSettings:Secret=${JWT_SECRET}
      - AppSettings:SmtpUser=${SMTP_USER}
      - AppSettings:SmtpPass=${SMTP_PASS}
      - AppSettings:Secrets:GoogleClientId=${GOOGLE_CLIENT_ID}
      - AppSettings:Secrets:GoogleClientSecret=${GOOGLE_CLIENT_SECRET}
      - AppSettings:Secrets:GithubClientId=${GITHUB_CLIENT_ID}
      - AppSettings:Secrets:GithubClientSecret=${GITHUB_CLIENT_SECRET}
    depends_on:
      - db
    ports:
      - ${BACKEND_PORT}:80
    networks:
      - matcha-network
    restart: unless-stopped

  # ------------------------------------------------------------
  # React 18 - Frontend
  # ------------------------------------------------------------
  frontend:
    container_name: frontend
    build:
      context: ./src/frontend
      dockerfile: Dockerfile.dev
    environment:
      WATCHPACK_POLLING: "true"
      WDS_SOCKET_PORT: ${FRONTEND_PORT}
      PORT: ${FRONTEND_PORT}
      REACT_APP_BACKEND_PORT: ${BACKEND_PORT}
      REACT_APP_GOOGLE_OAUTH_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      REACT_APP_GOOGLE_OAUTH_REDIRECT: ${FRONTED_GOOGLE_OAUTH_REDIRECT}
      REACT_APP_GITHUB_OAUTH_CLIENT_ID: ${GITHUB_CLIENT_ID}
      REACT_APP_GITHUB_OAUTH_REDIRECT_URL: ${FRONTEND_GITHUB_OAUTH_REDIRECT_URL}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    volumes:
      - ./src/frontend/src:/usr/src/app/src
    networks:
      - matcha-network
    restart: unless-stopped

volumes:
  msdata:

networks:
  matcha-network:
    driver: bridge
